export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_LIST_OF_ARTICLES = 'GET_LIST_OF_ARTICLES';
export const GET_ARTICLE = 'GET_ARTICLE';

export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';